/**
 * Type definitions for CSV data structure
 */

export interface PriceEntry {
  timestamp: string;
  price: number;
}

export interface TripTerm {
  dateRange: string;
  startDate: Date;
  endDate: Date;
  priceHistory: PriceEntry[];
  currentPrice: number;
}

export interface YearGroup {
  year: number;
  terms: TripTerm[];
  isExpanded: boolean;
}

export interface CsvData {
  fileName: string;
  timestamps: string[];
  terms: TripTerm[];
  yearGroups: YearGroup[];
  lastUpdated: string;
  offerUrl?: string; // Optional URL to trip offer generated by ConfigManager
}

export interface ParsedCsvRow {
  dateRange: string;
  prices: (number | null)[];
}